repository:
  name: keepalived-k8scp
  description: keepalived container image for a staticpod on kubernetes controlplane
  homepage: https://hub.docker.com/r/curx/keepalived-k8scp
  topics: docker, image, container, staticpod, kubernetes

  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
