FROM alpine:3.11@sha256:a0ce0e57c6900f6f13cee6f1c1e0337cedd745ebc1bac226c61eb574667c6d04

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="keepalived-k8scp" \
  org.label-schema.version="1.3" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["entrypoint.sh"]

RUN apk -U --no-cache add keepalived

COPY ./overlay ./overlay-amd64 /
