FROM arm32v6/alpine:3.12@sha256:b7b182ccc0811af3fc00754c3cc744e45bc3d7d4f6ef9ee47071173f893dbfb0

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="keepalived-k8scp" \
  org.label-schema.version="1.3" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["entrypoint.sh"]

RUN apk -U --no-cache add keepalived

COPY ./overlay ./overlay-arm32v6 /
