FROM alpine:3.11@sha256:bcae378eacedab83da66079d9366c8f5df542d7ed9ab23bf487e3e1a8481375d

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="keepalived-k8scp" \
  org.label-schema.version="1.3" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["entrypoint.sh"]

RUN apk -U --no-cache add keepalived

COPY ./overlay ./overlay-amd64 /
