FROM arm64v8/alpine:3.11@sha256:b3f3def7cb32d957cda8e8253257d349e3af76188cde9ffa2622239d46c96616

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="keepalived-k8scp" \
  org.label-schema.version="1.3" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["entrypoint.sh"]

RUN apk -U --no-cache add keepalived

COPY ./overlay ./overlay-arm64v8 /
