FROM alpine:3.11@sha256:cb8a924afdf0229ef7515d9e5b3024e23b3eb03ddbba287f4a19c6ac90b8d221

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="keepalived-k8scp" \
  org.label-schema.version="1.3" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["entrypoint.sh"]

RUN apk -U --no-cache add keepalived

COPY ./overlay ./overlay-amd64 /
